# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - SPASS-CHS-TEST

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Node Setup
        uses: actions/setup-node@v6.2.0
        with: 
          node-version: 22

      - name: Node Deps
        working-directory: client
        run: npm install

      - name: Build Vite
        working-directory: client
        run: npm run build
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'SPASS-CHS-TEST'
          slot-name: 'Production'
          package: server

          



