applications:
  - name: van-ai-guided-data-entry
    memory: 1G
    disk_quota: 2G
    instances: 1
    buildpacks:
      - https://github.com/cloudfoundry/python-buildpack.git
    env:
      PYTHONPATH: "."
    path: .
    command: python -m server.main
